version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./src:/app/src

  backend:
    build: ./backend
    command: npm run start:dev
    container_name: taskmanager_backend
    environment:
      - PORT=3000
      - ENV=docker
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - db
    links:
      - db

  db:
    build: .docker/postgres
    container_name: taskmanager_db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/dbdata
    environment:
      - POSTGRES_PASSWORD=felipe1303
      - POSTGRES_DB=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: taskmanager_pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db
